//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.30 at 12:44:52 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.google.com/kml/ext/2.2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.google.kml.ext._2;
